BiCoN_web/urls.py
# Django imports
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('apps.clustering.urls')),
    path('admin/', admin.site.urls),
]

# Serve media files during debugging through the django server as well
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPLATE TODO check if can be used
# urlpatterns = [
#     # Examples:
#     # url(r'^blog/', include('blog.urls', namespace='blog')),
#
#     # provide the most basic login/logout functionality
#     url(r'^login/$', auth_views.login,
#         {'template_name': 'core/login.html'}, name='core_login'),
#     url(r'^logout/$', auth_views.logout, name='core_logout'),
#
#     # enable the admin interface
#     url(r'^admin/', admin.site.urls),
# ]

apps/clustering/urls.py
from django.urls import path

from .views import IndexView, AnalysisSetupView, submit_analysis, analysis_status, analysis_status_single, poll_status, \
    analysis_result, \
    results, bookmark, DocumentationView, AboutView, test, test_result

app_name = 'clustering'
urlpatterns = [
    # Index Page
    path('', IndexView.as_view(), name='index'),

    # Analysis setup page (overview page / first page)
    path('analysis/', AnalysisSetupView.as_view(), name='analysis_setup'),
    # Only for post-requests. If called via head, just redirect to status
    path('analysis/submit', submit_analysis, name='submit_job'),
    # Page to monitor current status of job
    path('analysis/status/<uuid:analysis_id>', analysis_status_single, name='analysis_status_single'),
    # Page to monitor current status of all the recent jobs
    path('analysis/status/', analysis_status, name='analysis_status'),
    # Url for polling the status of one task
    path('analysis/status/poll', poll_status, name='poll_status'),
    # Page for looking at one specific result
    path('analysis/result/<uuid:analysis_id>', analysis_result, name='analysis_result'),
    # Page for all the results
    path('analysis/results', results, name='analysis_results'),

    # TEST PAGE
    path('analysis/test_result', test_result, name='test_result'),
    path('analysis/test', test, name='test'),

    # Page to restore a session (bookmark a session)
    path('bookmark/<uuid:session_id>', bookmark, name='bookmark'),
    # Page for documentation and source
    path('documentation/', DocumentationView.as_view(), name='documentation'),
    path('about/', AboutView.as_view(), name='about'),
]

templates/clustering/analysis/results/result_single.html
{% extends "clustering/base/base_analysis.html" %}

{% block title %}BiCoN-Web analysis results{% endblock %}


{% block content %}
    {% load static %}
    <div class="card mt-4 ml-2" style="border: none">
        <h1 class="card-title">Result for: {{ job_identifier }}</h1>
    </div>

    <!-- Analysis PPI Graph -->
    <div class="card mt-4">
        <div class="card-body">
            <h2 class="card-title">Extracted subnetworks</h2>
            <p class="card-text">The color of a node corresponds to the mean difference in expression level
                between two
                clusters of patients.
            </p>

            <div class="container no-gutters">
                <div class="row">
                    <div class="col-2" style=" padding-right: 0; padding-left: 0">
                        <img class="img-fluid" src="{% static 'clustering/img/analysis/ppi_network_legend.png' %}"
                             style="height: 200px;">
                    </div>
                    <div class="col" style=" padding-right: 0; padding-left: 0">
                        <div id="ppi-graph-container" style="max-width: available; height: 400px; margin: auto"></div>
                    </div>
                </div>
            </div>
            <p>In the above graph, interactions between analysed genes are shown. The color corresponds to
                the mean difference in expression level between both groups.</p>
            <b>
                Download the network
                <a href="{% get_media_prefix %}{{ ppi_png }}" download> as png </a> or
                <a href="{% get_media_prefix %}{{ ppi_json }}" download> as json file </a>
            </b>
        </div>
    </div>

    <div class="card mt-4">
        <div class="card-body">
            <h2 class="card-title">Drugst.One</h2>
            <p>Find drug-targets and repurpose drugs based on the extracted subnetworks. <a href="https://drugst.one">More information</a></p>
            <div class="container">
                <div class="row">
                    <drugst-one id="netexp" config='{{ netex_config }}' network='{{ netex_network }}' style="width: 100%;"></drugst-one >
                </div>
            </div>
        </div>
    </div>

    <!-- Heatmap -->
    <div class="card mt-4">
        <div class="card-body">
            <h2 class="card-title">Heatmap</h2>
            <p>The heatmap shows resulting biclustering.</p>
            <img src="{% get_media_prefix %}{{ heatmap_png }}" class="img-fluid">

            <b>
                Download the heatmap
                <a href="{% get_media_prefix %}{{ heatmap_png }}" download> as png </a>
            </b>
        </div>

    </div>

    <!-- Survial Data -->
    {% if survival_plotly %}
        <div class="card mt-4">
            <div class="card-body">
                <h2 class="card-title">Survival Analysis</h2>
                <object type="text/html" data="{% get_media_prefix %}{{ survival_plotly }}"
                        style="width: 100%; height: 400px">
                </object>

            </div>
        </div>
    {% endif %}
    <!-- Patient Data -->
    {% if patient_metadata_head %}

        <div class="card mt-4">
            <div class="card-body">
                <h2>Patient Data</h2>
                <p>In the below table, the Jaccard Index of correlation between patient clusters (output by the
                    algorithm) and clinical events (e.g. metastasis) is shown. (E.g., which fraction of patients
                    in Cluster 1 has a lung metastasis).</p>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <!--- iterate over tables of metadata and display as table--->
                            <th scope="col">Group</th>
                            {% for key,value in patient_metadata_head.items %}
                                <th scope="col"> {{ value }} </th>
                            {% endfor %}
                        </tr>
                        </thead>

                        <tbody>
                        <tr>
                            <th>Group 1</th>
                            {% for key,value in patient_metadata_group_1.items %}
                                <th> {{ value }}</th>
                            {% endfor %}
                        </tr>

                        <tr>
                            <th>Group 2</th>
                            {% for key,value in patient_metadata_group_2.items %}
                                <th>{{ value }}</th>
                            {% endfor %}
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}

    <!-- Convergence Behaviour -->
    <div class="card mt-4">
        <div class="card-body">
            <h2 class="card-title">Convergence Behaviour</h2>
            <img src="{% get_media_prefix %}{{ convergence_png }}" class="img-fluid">

            <b>
                Download the convergence behaviour
                <a href="{% get_media_prefix %}{{ convergence_png }}" download> as png </a>
            </b>
        </div>
    </div>
    <!-- Convergence Behaviour -->

    <!-- Download Results -->
    {% if result_csv %}
    <div class="card mt-4">
        <div class="card-body">
            <h2 class="card-title">Download Results</h2>
            <b>
                Download the results
                <a href="{% get_media_prefix %}{{ result_csv }}" download> as csv file </a>
            </b>
        </div>
    </div>
    {% endif %}
    <!-- Download Results -->

{% endblock %}

<!--- Javascript block --->
{% block scripts %}
    <!-- Import javacript files -->
    <!--- sigma.js imports needed for PPI graph -->
    <script src="{% static 'clustering/js/sigma.js/src/sigma.core.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/conrad.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/utils/sigma.utils.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/utils/sigma.polyfills.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/sigma.settings.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/classes/sigma.classes.dispatcher.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/classes/sigma.classes.configurable.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/classes/sigma.classes.graph.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/classes/sigma.classes.camera.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/classes/sigma.classes.quad.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/classes/sigma.classes.edgequad.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/captors/sigma.captors.mouse.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/captors/sigma.captors.touch.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/sigma.renderers.canvas.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/sigma.renderers.webgl.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/sigma.renderers.svg.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/sigma.renderers.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/webgl/sigma.webgl.nodes.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/webgl/sigma.webgl.nodes.fast.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/webgl/sigma.webgl.edges.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/webgl/sigma.webgl.edges.fast.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/webgl/sigma.webgl.edges.arrow.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.labels.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.hovers.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.nodes.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edges.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edges.curve.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edges.arrow.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edges.curvedArrow.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edgehovers.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edgehovers.curve.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edgehovers.arrow.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.edgehovers.curvedArrow.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/canvas/sigma.canvas.extremities.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/svg/sigma.svg.utils.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/svg/sigma.svg.nodes.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/svg/sigma.svg.edges.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/svg/sigma.svg.edges.curve.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/svg/sigma.svg.labels.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/renderers/svg/sigma.svg.hovers.def.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/middlewares/sigma.middlewares.rescale.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/middlewares/sigma.middlewares.copy.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/misc/sigma.misc.animation.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/misc/sigma.misc.bindEvents.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/misc/sigma.misc.bindDOMEvents.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/src/misc/sigma.misc.drawHovers.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/plugins/sigma.renderers.customShapes/shape-library.js' %}"></script>
    <script src="{% static 'clustering/js/sigma.js/plugins/sigma.renderers.customShapes/sigma.renderers.customShapes.js' %}"></script>
    <!-- END SIGMA IMPORTS -->
    <script src="{% static 'clustering/js/sigma.js/plugins/sigma.parsers.json/sigma.parsers.json.js' %}"></script>


    <!-- script for generation of PPI graph--->
    <script>
        sigma.parsers.json('{% get_media_prefix %}{{ppi_json}}', {
            container: 'ppi-graph-container',
            settings: {
                defaultNodeColor: '#ec5148'
            }
        });
    </script>

{% endblock %}

templates/clustering/analysis/results/results.html
{% extends "clustering/base/base_analysis.html" %}

{% block title %}BiCoN-Web analysis results overview{% endblock %}


{% block content %}
    <div class="card mt-4">
        <div class="card-body">
            <h1 class="card-title">Results</h1>
            <p class="card-text">Overview of all the finished jobs</p>
            <br/>
            <div class="table-responsive">
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                    <tr>
                        <!--- iterate over tables of metadata and display as table--->
                        <th scope="col">Job Name</th>
                        <th scope="col">Submission Date</th>
                        <th scope="col">Job ID</th>
                        <th scope="col">Completion Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">More information</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for job in previous_jobs %}

                        <tr>
                            <td>{{ job.job_name}}</td>
                            <td>{{ job.submit_time }}</td>
                            <td>{{ job.job_id }}</td>
                            <td>{{ job.finished_time }}</td>
                            <td>{{ job.status }}</td>
                            {% if job.status == 'SUCCESS' %}
                                <td><a href="{% url 'clustering:analysis_result' job.job_id %}">Click me</a></td>
                            {% else %}
                                <td><a href="{% url 'clustering:analysis_status_single' job.job_id %}">Click me</a></td>

                            {% endif %}
                        </tr>
                    {% empty %}
                        There are currently no submitted jobs.
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}