BiCoN_web/urls.py
# Django imports
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('apps.clustering.urls')),
    path('admin/', admin.site.urls),
]

# Serve media files during debugging through the django server as well
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPLATE TODO check if can be used
# urlpatterns = [
#     # Examples:
#     # url(r'^blog/', include('blog.urls', namespace='blog')),
#
#     # provide the most basic login/logout functionality
#     url(r'^login/$', auth_views.login,
#         {'template_name': 'core/login.html'}, name='core_login'),
#     url(r'^logout/$', auth_views.logout, name='core_logout'),
#
#     # enable the admin interface
#     url(r'^admin/', admin.site.urls),
# ]

apps/clustering/urls.py
from django.urls import path

from .views import IndexView, AnalysisSetupView, submit_analysis, analysis_status, analysis_status_single, poll_status, \
    analysis_result, \
    results, bookmark, DocumentationView, AboutView, test, test_result

app_name = 'clustering'
urlpatterns = [
    # Index Page
    path('', IndexView.as_view(), name='index'),

    # Analysis setup page (overview page / first page)
    path('analysis/', AnalysisSetupView.as_view(), name='analysis_setup'),
    # Only for post-requests. If called via head, just redirect to status
    path('analysis/submit', submit_analysis, name='submit_job'),
    # Page to monitor current status of job
    path('analysis/status/<uuid:analysis_id>', analysis_status_single, name='analysis_status_single'),
    # Page to monitor current status of all the recent jobs
    path('analysis/status/', analysis_status, name='analysis_status'),
    # Url for polling the status of one task
    path('analysis/status/poll', poll_status, name='poll_status'),
    # Page for looking at one specific result
    path('analysis/result/<uuid:analysis_id>', analysis_result, name='analysis_result'),
    # Page for all the results
    path('analysis/results', results, name='analysis_results'),

    # TEST PAGE
    path('analysis/test_result', test_result, name='test_result'),
    path('analysis/test', test, name='test'),

    # Page to restore a session (bookmark a session)
    path('bookmark/<uuid:session_id>', bookmark, name='bookmark'),
    # Page for documentation and source
    path('documentation/', DocumentationView.as_view(), name='documentation'),
    path('about/', AboutView.as_view(), name='about'),
]

apps/clustering/models.py
from celery.states import FAILURE, IGNORED, PENDING, RECEIVED, RETRY, REVOKED, STARTED, SUCCESS
from django.contrib.auth.models import User
from django.db import models


class Job(models.Model):
    SUBMITTED = 'SUBMITTED'
    JOB_STATES = [
        (SUBMITTED, 'submitted'),
        (FAILURE, 'failed'),
        (IGNORED, 'ignored'),
        (PENDING, 'pending'),
        (RECEIVED, 'received'),
        (RETRY, 'retry'),
        (REVOKED, 'revoked'),
        (STARTED, 'started'),
        (SUCCESS, 'success')
    ]

    job_id = models.UUIDField(primary_key=True, editable=False)
    job_name = models.CharField(max_length=30, default='', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    session_id = models.CharField(max_length=33, blank=True)
    submit_time = models.DateTimeField(editable=False)
    status = models.CharField(
        max_length=9,
        choices=JOB_STATES,
    )
    finished_time = models.DateTimeField(null=True, blank=True)
    # ppi_json = models.TextField(blank=True)
    result_csv = models.FileField(upload_to=f'clustering/result/', blank=True)
    ppi_json = models.FileField(upload_to=f'clustering/ppi/')
    # survival_plotly = models.TextField(blank=True)
    survival_plotly = models.FileField(upload_to=f'clustering/survival/')
    ppi_png = models.FileField(upload_to=f'clustering/ppi/')
    heatmap_png = models.FileField(upload_to=f'clustering/heatmap/')
    convergence_png = models.FileField(upload_to=f'clustering/convergence/')
    netex_json = models.FileField(upload_to=f'clustering/netex/', null=True)

    def __str__(self):
        return f'Job ID: {self.job_id} submitted on {self.submit_time}, finished on {self.finished_time}'


class PpiNetworkCache(models.Model):
    # Network id (same as NDEx UUID)
    network_id = models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)
    # Date and time this cached version has been last modified/updated
    last_modified = models.DateTimeField(auto_now=True)
    # Date and time the NDEx PPI network has been modified
    data_last_modified = models.DateTimeField()
    # The actual cached network data as string
    network_string = models.TextField()

    def __str__(self):
        return f'Network: {self.network_id} last modified on {self.last_modified}. NDEx last modified on {self.data_last_modified}'

apps/clustering/views.py
import datetime
import json
import re
import uuid

import pandas as pd
from celery.result import AsyncResult
from celery.states import SUCCESS, FAILURE
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views.generic import TemplateView
from importlib_metadata import version
from django.templatetags.static import static


from .models import Job
from .tasks import run_algorithm


class IndexView(TemplateView):
    template_name = "clustering/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'home'
        return context


class AnalysisSetupView(TemplateView):
    template_name = "clustering/analysis/analysis_setup.html"

    def get_context_data(self, **kwargs):
        # Create new session if none is found
        if not self.request.session.session_key:
            self.request.session.create()

        context = super().get_context_data(**kwargs)
        context['navbar'] = 'analysis'
        context['groupbar'] = 'setup_analysis'
        return context


def submit_analysis(request):
    """
    Parse the options and files from the given POST request (generated by AnalysisSetupView)
    and start analysis task with Celery
    """
    # For debugging
    print(f'===== POST REQUEST: {request.POST}')
    print(f'===== REQUEST FILES: {request.FILES}')

    # ========== Test if all the parameters are set correctly ==========
    # Check parameters before parsing to gather a complete list of errors
    # error_list contains the error messages if errors are found
    error_list = list()
    post_keys = request.POST.keys()
    file_keys = request.FILES.keys()
    # --- Step 0: Populate session_id
    if not request.session.session_key:
        error_list.append('No session_id found. Please enable cookies in your browser and try again')

    # --- Step 1: Expression Data
    if 'expression-data' not in post_keys:
        error_list.append('No "Gene Expression Data" option selected')

    elif request.POST['expression-data'] == 'custom' and 'expression-data-file' not in file_keys:
        error_list.append('"Custom expression data" selected but no file uploaded')

    # --- Step 2: PPI Network
    if 'ppi-network' not in post_keys:
        error_list.append('No "PPI-Network" option selected')

    elif request.POST['ppi-network'] == 'custom' and 'ppi-network-file' not in file_keys:
        error_list.append('"Custom PPI-Network" selected but no file uploaded')

    # --- Step 3: Meta data
    if 'use_metadata' in post_keys:
        if 'survival-col' not in post_keys:
            error_list.append('"Survival column name" missing')
        elif request.POST['use_metadata'] == 'yes':
            if not request.POST['survival-col'].strip():
                error_list.append('"Survival column name" is empty')
            if 'survival-metadata-file' not in file_keys:
                error_list.append('"Use additional metadata" selected but no "Survival metadata file" not uploaded')

    # --- Step 4: Algorithm parameters (Required)
    if 'L_g_min' not in post_keys:
        error_list.append('"L_g_min" not specified')
    else:
        tmp_var = request.POST['L_g_min']
        try:
            int(tmp_var)
        except (ValueError, TypeError):
            error_list.append('"L_g_min" cannot be empty and must be a number')

    if 'L_g_max' not in post_keys:
        error_list.append('"L_g_max" not specified')
    else:
        tmp_var = request.POST['L_g_max']
        try:
            int(tmp_var)
        except (ValueError, TypeError):
            error_list.append('"L_g_max" cannot be empty and must be a number')

    # --- Step 5: Job name (Optional)
    if 'job_name' not in post_keys:
        error_list.append('"job_name" not specified')

    else:
        tmp_var = request.POST['job_name']
        reg = re.compile(r'^[a-zA-Z0-9-_\s]+$')
        if not reg.match(tmp_var) and tmp_var:
            error_list.append('"Job name" contains not allowed characters')

        if len(tmp_var) > 30:
            error_list.append('""Job name" is longer than 30 characters')


    # ========== Parse algorithm parameters from post request ==========
    session_id = None
    algorithm_parameters = dict()

    # --- Step 0: Populate session_id
    if request.user.is_authenticated:
        pass  # Add user auth here and set session_id to user
    else:
        session_id = request.session.session_key

    # --- Step 1: Expression Data
    expr_data_selection = request.POST['expression-data']
    expr_data_str = None
    apply_log2 = False
    apply_z_transformation = False

    # Parse expression network from uploaded file into string (easier to serialize than file object)
    if expr_data_selection == 'custom':
        try:
            expr_data_str = request.FILES['expression-data-file'].read().decode('utf-8')
        except UnicodeDecodeError:
            error_list.append("The expression data file is not a plain text file (cannot be decoded in utf-8)")

        apply_log2 = 'expression-data-log2' in request.POST.keys()
        apply_z_transformation = 'z-score-transformation' in request.POST.keys()

    # --- Step 2: PPI Network
    ppi_network_selection = request.POST['ppi-network']
    ppi_network_str = None

    # Parse ppi network from uploaded file into string (easier to serialize than file object)
    if ppi_network_selection == 'custom':
        try:
            ppi_network_str = request.FILES['ppi-network-file'].read().decode('utf-8')

        except UnicodeDecodeError:
            error_list.append("The ppi network file is not a plain text file (cannot be decoded in utf-8)")

    # --- Step 3: Meta data
    survival_col_name = None
    clinical_df = None
    use_metadata = False

    if 'use_metadata' in request.POST:
        if request.POST['use_metadata'] == 'yes':  # Set parameter for metadata analysis if desired
            print("USING METADATA")
            use_metadata = True
            if 'survival-col' in request.POST and 'survival-metadata-file' in request.FILES:
                survival_col_name = request.POST['survival-col'].strip()
                clinical_df = pd.read_csv(request.FILES['survival-metadata-file'])
        else:  # Set the variables to empty, default checkbox for example data
            pass

    algorithm_parameters['use_metadata'] = use_metadata
    algorithm_parameters['survival_col_name'] = survival_col_name
    algorithm_parameters['clinical_df'] = clinical_df

    # --- Step 4: Algorithm parameters (Required)
    L_g_min = int(request.POST['L_g_min'])
    L_g_max = int(request.POST['L_g_max'])

    # --- Step 4.1: Algorithm parameters (Optional)
    if request.POST['clustering_advanced'] == 'yes':
        nbr_iter = int(request.POST.get("nbr_iter"))
        gene_set_size = int(request.POST.get("gene_set_size", 2000))
        nbr_ants = int(request.POST.get("nbr_ants", 30))
        evap = float(request.POST.get("evap", 0.3))
        pher_sig = float(request.POST.get("pher", 1))
        hi_sig = float(request.POST.get("hisig", 1))
        epsilon = float(request.POST.get("stopcr", 0.02))

        algorithm_parameters['max_iter'] = nbr_iter
        algorithm_parameters['size'] = gene_set_size
        algorithm_parameters['k'] = nbr_ants
        algorithm_parameters['evaporation'] = evap
        algorithm_parameters['b'] = pher_sig
        algorithm_parameters['a'] = hi_sig
        algorithm_parameters['eps'] = epsilon

    # If the error list is not empty, redirect back to analysis setup and display errors
    # Todo redirect back to analysis setup instead of displaying on submit...
    if error_list:
        print("Input was incorrect. Redirecting back to setup page")
        return render(request, "clustering/analysis/analysis_setup.html", context={
            'navbar': 'analysis',
            'groupbar': 'setup_analysis',
            'error_list': error_list
        })

    print('All the given data was parsed: Starting clustering')

    # --- Step 4.2: Job name (Optional)
    job_name = request.POST['job_name'].strip()

    # ========== Save the task into the database (create a job) ==========
    task_id = uuid.uuid4()

    if session_id:
        job = Job(job_id=task_id, session_id=session_id, submit_time=timezone.now(),
                  status=Job.SUBMITTED, job_name=job_name)
        job.save()
    else:
        raise KeyError('session_id not found')

    # ========== Run the clustering algorithm ==========
    print('Running algorithm starteddd')
    # started_algorithm_id = run_algorithm.delay(job, expr_data_selection, expr_data_str, ppi_network_selection,
    #                                            ppi_network_str, False, gene_set_size, L_g_min, L_g_max, n_proc=1,
    #                                            a=hi_sig, b=pher_sig, K=nbr_ants, evaporation=evap, th=0.5, eps=epsilon,
    #                                            times=6, clusters=2, cost_limit=5, max_iter=nbr_iter, opt=None,
    #                                            show_pher=False, show_plot=False, save=None, show_nets=False).id

    run_algorithm.apply_async(args=[job, expr_data_selection, expr_data_str, ppi_network_selection, ppi_network_str,
                                    L_g_min, L_g_max, apply_log2, apply_z_transformation],
                            kwargs=algorithm_parameters,
                            task_id=str(task_id), ignore_result=True)


    print(f'redicreting to analysis_status')
    return HttpResponseRedirect(reverse('clustering:analysis_status_single', kwargs={'analysis_id': task_id}))


def test(request):
    old_key = request.session.session_key
    request.session.cycle_key()
    return HttpResponse(f'old key {old_key} : new key {request.session.session_key}')


def test_result(request):

templates/clustering/analysis_status.html
{% extends "clustering/base_analysis.html" %}

{% block title %}BiCoN-Web analysis status{% endblock %}

{% block custom_css %}
    {% load static %}
{% endblock %}


{% block content %}
    <div class="card mt-4">
        <div class="card-body">
            <h1 class="card-title">Job status overview</h1>
            <p class="card-text">View all the previously submitted and running jobs</p>

            {% for job in previous_jobs %}
                <div class="card mt-4">
                    <div class="card-body">
                        {% if job.job_name %}
                            <h2 class="card-title">Task Name: {{ job.job_name }}</h2>
                        {% else %}
                            <h2 class="card-title">Task ID: {{ job.job_id }}</h2>
                        {% endif %}
                        <p class="card-text">
                            <strong>Submitted on: </strong>{{ job.submit_time }}<br>
                            <strong>Status: </strong><span id="state-{{ job.job_id }}"></span>
                        </p>
                        <strong>Progress:</strong>
                        <div class="progress">
                            <div id="bar-{{ job.job_id }}" class="progress-bar" style="width: 0%;">0 &#37;</div>
                        </div>
                        <div class="mt-2 float-right">
                            <a class="btn btn-primary"
                               href="{% url 'clustering:analysis_status_single' job.job_id %}">More details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

{% block scripts %}
    {% load static %}
    <script src="{% static 'clustering/js/status_multiple.js' %}"></script>
    <script>
        // Run the update task_status function
        {% for job in previous_jobs %}
            update_status('{{ csrf_token }}', '{{ job.job_id }}', '{% url 'clustering:poll_status' %}');
        {% endfor %}
    </script>
{% endblock %}

templates/clustering/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}BiCoN-Web BASE TEMPLATE{% endblock %}</title>

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'clustering/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template TODO add credits?-->
    <link href="{% static 'clustering/css/shop-item.css' %}" rel="stylesheet">
    {% block custom_template_css %}{% endblock %}
    {% block custom_css %}{% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'clustering:index' %}">BiCoN-Web</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item {% if navbar == 'home' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'clustering:index' %}">Home
{#                        <span class="sr-only">(current)</span>#}
                    </a>
                </li>
                <li class="nav-item {% if navbar == 'analysis' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'clustering:analysis_setup' %}">Analysis</a>
                </li>
                <li class="nav-item {% if navbar == 'documentation' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'clustering:documentation' %}">Documentation</a>
                </li>
                <li class="nav-item {% if navbar == 'sources' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'clustering:sources' %}">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container mb-5" style="min-height:100vh;">
    {% block empty_content %}

        <div class="row">
            {% block content %}

                <div class="col-lg-9">

                    <div class="card mt-4">
                        <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
                        <div class="card-body">
                            <h3 class="card-title">Product Name</h3>
                            <h4>$24.99</h4>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente
                                dicta fugit
                                fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur
                                praesentium animi perspiciatis molestias iure, ducimus!</p>
                            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
                            4.0 stars
                        </div>
                    </div>
                    <!-- /.card -->

                    <div class="card card-outline-secondary my-4">
                        <div class="card-header">
                            Product Reviews
                        </div>
                        <div class="card-body">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam
                                inventore,
                                similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat
                                laborum.
                                Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam
                                inventore,
                                similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat
                                laborum.
                                Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam
                                inventore,
                                similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat
                                laborum.
                                Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <a href="#" class="btn btn-success">Leave a Review</a>
                        </div>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col-lg-9 -->
            {% endblock %}
        </div>
    {% endblock %}
</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-4 bg-dark footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright  2020 &copy;
            <u><a href="https://biomedical-big-data.de" target="_blank" rel="noopener noreferrer" style="color:inherit;">
                Big Data in Biomedicine
            </a></u>
            and
            <u><a href="https://compsysmed.de" target="_blank" rel="noopener noreferrer" style="color:inherit;">
                Computational Systems Medicine
            </a></u>
        </p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'clustering/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'clustering/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

{% block scripts %}
{% endblock %}

</body>

</html>

templates/clustering/base_analysis.html
{% extends "clustering/base.html" %}

{% block title %}BiCoN-Web ANALYSIS TEMPLATE{% endblock %}

{% block custom_template_css %}
    <style>
        .list-group > .list-group > .list-group-item {
            padding-left: 2.5rem;
        }

    </style>
{% endblock %}

{% block empty_content %}
    <div class="row">
        <div class="col-lg-3">
            <h1 class="my-4">Analysis Menu</h1>
            <div class="list-group">
                <a href="{% url 'clustering:analysis_setup' %}"
                   class="list-group-item {% if groupbar == 'setup_analysis' %}active{% endif %}">Setup new analysis</a>
                <a href="{% url 'clustering:analysis_status' %}" class="list-group-item {% if groupbar == 'submitted_analysis' %}active{% endif %}">Job
                    status</a>
                {% if groupbar == 'single_status' %}
                    <div class="list-group">
                        <a href="#" class="list-group-item active">> Single job status</a>
                    </div>
                {% endif %}
                <a href="{% url 'clustering:analysis_results' %}"
                   class="list-group-item {% if groupbar == 'all_results' %}active{% endif %}">Results</a>
                {% if groupbar == 'single_result' %}
                    <div class="list-group">
                        <a href="#" class="list-group-item active">> Single result</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
            {% block content %}

                <div class="card mt-4">
                    <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
                    <div class="card-body">
                        <h3 class="card-title">Product Name</h3>
                        <h4>$24.99</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dicta
                            fugit
                            fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur
                            praesentium animi perspiciatis molestias iure, ducimus!</p>
                        <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
                        4.0 stars
                    </div>
                </div>
                <!-- /.card -->

                <div class="card card-outline-secondary my-4">
                    <div class="card-header">
                        Product Reviews
                    </div>
                    <div class="card-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore,
                            similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat
                            laborum.
                            Sequi mollitia, necessitatibus quae sint natus.</p>
                        <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                        <hr>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore,
                            similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat
                            laborum.
                            Sequi mollitia, necessitatibus quae sint natus.</p>
                        <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                        <hr>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore,
                            similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat
                            laborum.
                            Sequi mollitia, necessitatibus quae sint natus.</p>
                        <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                        <hr>
                        <a href="#" class="btn btn-success">Leave a Review</a>
                    </div>
                </div>
                <!-- /.card -->
            {% endblock %}
        </div>
        <!-- /.col-lg-9 -->

    </div>
{% endblock %}

templates/clustering/index.html
{% extends "clustering/base/base.html" %}

{% block title %}BiCoN-Web{% endblock %}

{% block empty_content %}
    <!-- Jumbotron Header -->
    {% load static %}
    <header class="jumbotron my-4">
        <h1 class="display-3">BiCoN</h1>
        <p class="lead">Biclustering constrained by networks (BiCoN) is a powerful new systems medicine tool to stratify patients while elucidating disease mechanisms. BiCoN is a network-constrained biclustering approach which restricts
            biclusters to functionally related genes connected in molecular interaction networks and maximizes the
            expression difference between two groups of patients.</p>
    </header>

    <!-- Page Features -->
    <div class="row text-center">

        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <img class="card-img-top" src="{% static 'clustering/img/index/logo.svg' %}" alt="">
                <div class="card-body">
                    <h4 class="card-title">Analysis</h4>
                    <p class="card-text">
                        Submit a new analysis on your own data or use our test data. Check the status of the submitted
                        jobs and view the result of the finished ones.
                    </p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'clustering:analysis_setup' %}" class="btn btn-primary">Start analysis</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <img class="card-img-top" src="{% static 'clustering/img/index/Documentation_normal_light.svg' %}" alt="">
                <div class="card-body">
                    <h4 class="card-title">Documentation</h4>
                    <p class="card-text">
                        Learn how to use BiCoN: Upload your data, set the parameters and visualize the results.
                    </p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'clustering:documentation' %}" class="btn btn-primary">Learn how to</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <img class="card-img-top" src="{% static 'clustering/img/index/About.svg' %}" alt="">
                <div class="card-body">
                    <h4 class="card-title">About</h4>
                    <p class="card-text">Read about the tool, learn how to cite it or contact us.</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'clustering:about' %}" class="btn btn-primary">About this tool</a>
                </div>
            </div>
        </div>

    </div>
    <!-- /.row -->

    <style type="text/css">
        .card-img-top {
            width: 100%;
            height: 20vw;
            object-fit: cover;
        }
    </style>

{% endblock %}